# fly.toml app configuration file generated for moonlight-beta-privacy-provider-a on 2026-01-29T20:55:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'moonlight-beta-privacy-provider-a'
primary_region = 'ams'

[build]

[env]
  PORT = '8080'
  MODE = 'development'
  LOG_LEVEL = 'TRACE' # Valid values: FATAL, ERROR, WARN, INFO, DEBUG, TRACE

  # DATABASE
  # DATABASE_URL=set by fly.io provisioned postgres

  # STELLAR RELATED
  NETWORK = 'testnet'
  NETWORK_FEE = '1000000000' #stroops
  CHANNEL_ASSET_CONTRACT_ID='CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC'
  CHANNEL_CONTRACT_ID = 'CDMZSHMT2AIL2UG7XBOHZKXM6FY3MUP75HAXUUSAHLGRQ2VWPGYKPM5T'
  CHANNEL_AUTH_ID = 'CAF7DFHTPSYIW5543WBXJODZCDI5WF5SSHBXGMPKFOYPFRDVWFDNBGX7'
  CHANNEL_ASSET_CODE = 'XLM'

  # PROVIDER MANAGEMENT
  # GAIW4NXJOI5BQMDUPUUT2KNMSYPL3SZY45XCUDYYWM4KEJIXW5MO6DRE
  # PROVIDER_SK=set in fly.io env secrets
  OPEX_PUBLIC = 'GAKKWPIJFCWX4HFUBTKOBP2JLWIQTNBS5EYWEK4RLBXO37IWB5SSDZYX'
  # OPEX_SECRET=set in fly.io env secrets

  # SERVICE
  SERVICE_DOMAIN = 'moonlight-beta-privacy-provider-a.fly.dev'
  SERVICE_FEE = '100' #stroops
  # SERVICE_AUTH_SECRET=set in fly.io env secrets

  # AUTH
  CHALLENGE_TTL = '900' #15m
  SESSION_TTL = '21600' #6h

  # MEMPOOL CONFIGURATION
  MEMPOOL_SLOT_CAPACITY = '100'
  MEMPOOL_EXPENSIVE_OP_WEIGHT = '10'
  MEMPOOL_CHEAP_OP_WEIGHT = '1'
  MEMPOOL_EXECUTOR_INTERVAL_MS = '5000'
  MEMPOOL_VERIFIER_INTERVAL_MS = '10000'
  MEMPOOL_TTL_CHECK_INTERVAL_MS = '60000'

[processes]
  app = 'deno task serve'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

  [[http_service.checks]]
    interval = "5s"
    timeout = "3s"
    grace_period = "60s"
    method = "GET"
    path = "/api/v1/stellar/auth?account=GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF"

[deploy]
  strategy = "bluegreen"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
